date_today:
  name: Get Nepali Date
  description: Get current Nepali date
  fields: {}

generate_password:
  name: Generate Password
  description: Generate a new password with specified parameters
  fields:
    length:
      name: Length
      description: Length of the password to generate
      required: false
      default: 12
      example: 12
      selector:
        number:
          min: 8
          max: 64
          mode: box
    include_special:
      name: Include Special Characters
      description: Whether to include special characters in the password
      required: false
      default: true
      selector:
        boolean:

generate_pin:
  name: Generate PIN
  description: Generate a numeric PIN
  fields:
    length:
      name: Length
      description: Length of the PIN
      required: false
      default: 4
      example: 4
      selector:
        number:
          min: 4
          max: 12
