name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip custom component directory
        run: |
          cd custom_components/sapi
          zip -r ../../sapi.zip .

      - name: Generate release notes
        id: release_notes
        run: |
          changelog=$(awk '/^## \[/,0' CHANGELOG.md | awk 'NR==1 {next} /^[^#]/ {print} /^## \[/ {exit}')
          echo "CHANGES=$changelog" >> $GITHUB_ENV
          echo "FULL_CHANGELOG=[Read the full changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ env.CHANGES }}\n\n${{ env.FULL_CHANGELOG }}

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sapi.zip
          asset_name: sapi.zip
          asset_content_type: application/zip

      - name: Update HACS repository
        uses: hacs/action@main
        with:
          category: integration
