name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip custom component directory
        run: |
          cd custom_components/sapi
          zip -r ../../sapi.zip .

      - name: Generate release notes
        id: release_notes
        run: |
          changelog=$(awk '/^## \[/,0' CHANGELOG.md | awk 'NR==1 {next} /^[^#]/ {print} /^## \[/ {exit}')
          notes="${changelog}\n\n[Read the full changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)"
          echo "::set-output name=notes::$notes"

  create-release:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ steps.prepare-release.outputs.notes }}

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sapi.zip
          asset_name: sapi.zip
          asset_content_type: application/zip

  update-hacs:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update HACS repository
        uses: hacs/action@main
        with:
          category: integration
