name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate release notes
        id: generate_notes
        run: |
          # Extract changelog for the specific version
          changelog=$(awk '/^## \['"$(echo ${{ github.ref_name }} | sed 's/^v//')"'\]/ {flag=1; print; next} /^## \[/ {flag=0} flag' CHANGELOG.md)

          # If no changelog found, use a default message
          if [ -z "$changelog" ]; then
            changelog="No changelog entries found."
          fi

          # Add read more link
          changelog+=$'\n\n[Read the full changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)'

          # Write to release notes file
          echo "$changelog" > release_notes.md

      - name: Zip custom component directory
        run: |
          cd custom_components/sapi
          zip -r ../../sapi.zip .

      - name: Create Release
        id: create_release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHB_TOKEN }}
          script: |
            const fs = require('fs');
            const changelog = fs.readFileSync('release_notes.md', 'utf8');

            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref.replace('refs/tags/', ''),
              name: `Release ${context.ref.replace('refs/tags/', '')}`,
              body: changelog,
              draft: false,
              prerelease: false
            });

            return response.data.upload_url;

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.result }}
          asset_path: ./sapi.zip
          asset_name: sapi.zip
          asset_content_type: application/zip

      - name: Update HACS repository
        uses: hacs/action@main
        with:
          category: integration
