name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate release notes
        run: |
          # Extract changelog for the specific version
          changelog=$(awk '/^## \['"$(echo ${{ github.ref_name }} | sed 's/^v//')"'\]/ {flag=1; print; next} /^## \[/ {flag=0} flag' CHANGELOG.md)

          # If no changelog found, use a default message
          if [ -z "$changelog" ]; then
            changelog="No changelog entries found."
          fi

          # Add read more link
          changelog+=$'\n\n[Read the full changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)'

          # Write to release notes file
          echo "$changelog" > release_notes.md

      - name: Zip custom component directory
        run: |
          cd custom_components/sapi
          zip -r ../../sapi.zip .

      - name: Create Release and Upload Asset
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHB_TOKEN }}
          script: |
            const fs = require('fs');
            const { readFile } = require('fs/promises');
            const changelog = fs.readFileSync('release_notes.md', 'utf8');
            const tag = context.ref.replace('refs/tags/', '');

            // Create the release
            const createReleaseResponse = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `Release ${tag}`,
              body: changelog,
              draft: false,
              prerelease: false
            });

            // Upload the asset
            const uploadUrl = createReleaseResponse.data.upload_url;
            const zipFile = await readFile('./sapi.zip');

            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: createReleaseResponse.data.id,
              name: 'sapi.zip',
              data: zipFile
            });

      - name: Update HACS repository
        uses: hacs/action@main
        with:
          category: integration
