name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate release notes
        id: generate_changelog
        run: |
          changelog=$(awk '/^## / {if (found) exit; found=1} found' CHANGELOG.md)
          if [ -z "$changelog" ]; then
            changelog="No changelog entries found."
          fi
          # Use EOF to handle multiline output
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Zip custom component directory
        run: |
          cd custom_components/sapi
          zip -r ../../sapi.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ steps.generate_changelog.outputs.changelog }}

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sapi.zip
          asset_name: sapi.zip
          asset_content_type: application/zip

      - name: Update HACS repository
        uses: hacs/action@main
        with:
          category: integration
